# Generated by Django 3.1.5 on 2021-01-19 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_like_postview'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='link_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
