# Generated by Django 3.1.5 on 2021-01-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
