# Generated by Django 3.1.5 on 2021-01-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210124_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
